# Generated by Django 4.1.3 on 2023-05-09 17:13

import apps.licenses.models
import apps.licenses.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Registro"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z áÁéÉíÍóÓúÚñÑ.]*[a-zA-Z áÁéÉíÍóÓúÚñÑ.]$",
                                message="Solo puede ingresar letras",
                            )
                        ],
                        verbose_name="Nombre Documento",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creada"
                    ),
                ),
                (
                    "grant_date",
                    models.DateField(
                        validators=[apps.licenses.validators.DateInFutureValidator()],
                        verbose_name="Fecha de otorgamiento",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "ACTIVO"), (2, "EN PROCESO"), (3, "VENCIDO")],
                        default=1,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Observación",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.licenses.models.model_upload_image,
                        verbose_name="Subir Documento",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "associated_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="associated_processes",
                        to="base.process",
                        verbose_name="Proceso asociado",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="base.entity",
                        verbose_name="Entidad que certifica",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="base.process",
                        verbose_name="Proceso",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="base.employee",
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "ordering": ("created_date",),
            },
        ),
    ]
