# Generated by Django 4.1.3 on 2023-05-09 17:13

import SISGDDO.storage
import apps.base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("acronym", models.CharField(max_length=3)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        null=True,
                        verbose_name="Categoría Científica",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                (
                    "identification",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="Carnet de indentidad",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Entidad")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LogoEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "logo1",
                    models.ImageField(
                        storage=SISGDDO.storage.OverwriteStorage(),
                        upload_to="logo/",
                        verbose_name="Logo principal",
                    ),
                ),
                (
                    "logo2",
                    models.ImageField(
                        storage=SISGDDO.storage.OverwriteStorage(),
                        upload_to="logo/",
                        verbose_name="Logo secundario",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(max_length=15, verbose_name="Código"),
                ),
                (
                    "edition",
                    models.CharField(
                        default="00", max_length=3, verbose_name="Edición"
                    ),
                ),
                (
                    "revision",
                    models.CharField(
                        default="00", max_length=3, verbose_name="Revisión"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "responsible",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.employee",
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(max_length=15, verbose_name="Código"),
                ),
                (
                    "edition",
                    models.CharField(
                        default="00", max_length=3, verbose_name="Edición"
                    ),
                ),
                (
                    "revision",
                    models.CharField(
                        default="00", max_length=3, verbose_name="Revisión"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.base.models.model_upload_image,
                        verbose_name="Subir Archivo",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="base.process",
                        verbose_name="Proceso",
                    ),
                ),
            ],
            options={
                "ordering": ("process__order", "abbreviation", "name"),
            },
        ),
        migrations.CreateModel(
            name="InfoEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_reserve",
                    models.BooleanField(default=False, verbose_name="es reserva"),
                ),
                (
                    "init_date_reserve",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha de inicio como reserva de cuadro",
                    ),
                ),
                (
                    "finish_date_reserve",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha de terminación como reserva de cuadro",
                    ),
                ),
                (
                    "image_reserve",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.base.models.model_upload_image,
                        verbose_name="imagen de la reserva",
                    ),
                ),
                (
                    "spreadsheet_reserve",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.base.models.model_upload_image,
                        verbose_name="planilla de la reserva",
                    ),
                ),
                (
                    "is_executive",
                    models.BooleanField(default=False, verbose_name="es cuadro"),
                ),
                (
                    "init_date_executive",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha de inicio como cuadro",
                    ),
                ),
                (
                    "finish_date_executive",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="fecha de terminación como cuadro",
                    ),
                ),
                (
                    "image_executive",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.base.models.model_upload_image,
                        verbose_name="imagen del Cuadro",
                    ),
                ),
                (
                    "spreadsheet_executive",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.base.models.model_upload_image,
                        verbose_name="planilla del cuadro",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="base.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.position",
                verbose_name="Cargo",
            ),
        ),
    ]
