# Generated by Django 4.1.3 on 2022-12-20 00:11

import SISGDDO.storage
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="accion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tratamiento",
                    models.CharField(max_length=60, verbose_name="Tratamiento*"),
                ),
                (
                    "fecha_cumplir",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha a Cumplir*"
                    ),
                ),
                (
                    "seguimiento",
                    models.CharField(max_length=60, verbose_name="Seguimiento*"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
        ),
        migrations.CreateModel(
            name="accion_realizada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(verbose_name="Fecha acción realizada*")),
                (
                    "nombre_accion",
                    models.CharField(max_length=150, verbose_name="Nombre acción*"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="area",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=65, null=True, unique=True, verbose_name="nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="CambiarLogotipo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateField(
                        default="2022-12-20",
                        verbose_name="Fecha de Cambio del Logotipo",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        storage=SISGDDO.storage.OverwriteStorage(),
                        upload_to="logo/",
                        verbose_name="Logo*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="clasificacion_dibujo_modelo_industrial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Nombre clasificación de Dibujo y Modelo Industrial",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="clasificacion_elemento_figurativo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Clasificación de Elemento Figurativo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="clasificacion_patente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Nombre clasificacion de patente",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="clasificacion_productos_servicios",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Nombre de clasificación*",
                    ),
                ),
                (
                    "producto",
                    models.BooleanField(default=False, verbose_name="Es un producto"),
                ),
                (
                    "servicio",
                    models.BooleanField(default=False, verbose_name="Es un servicio"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="clasificacion_viena",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Nombre de la clasificación de Viena",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="cliente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Nombre y apellidos*"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="consecutivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no",
                    models.CharField(
                        max_length=10, null=True, unique=True, verbose_name="número*"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=10, null=True, unique=True, verbose_name="código*"
                    ),
                ),
                (
                    "fecha_entrada",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="fecha de entrada*"
                    ),
                ),
                (
                    "nombre_proyecto",
                    models.CharField(
                        max_length=250, null=True, unique=True, verbose_name="nombre*"
                    ),
                ),
                (
                    "aprobacion_consejo",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="aprobación Consejo Editorial",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="fecha de aprobación Consejo Editorial",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="fecha de inicio*"
                    ),
                ),
                (
                    "fecha_interrupcion",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="fecha de interrupción",
                    ),
                ),
                (
                    "causa_interrupcion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="causa de la interrupción",
                    ),
                ),
                (
                    "fecha_terminacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de fin"
                    ),
                ),
                (
                    "fecha_extension",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de extensión"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateField(null=True, verbose_name="fecha de cierre*"),
                ),
                (
                    "costo",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(9999999),
                        ],
                        verbose_name="costo*",
                    ),
                ),
                (
                    "observacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="observacion",
                    ),
                ),
                (
                    "informe_apertura",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ruta/",
                        verbose_name="informe apertura",
                    ),
                ),
                (
                    "informe_cierre",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ruta/",
                        verbose_name="informe cierre",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=models.SET("Área eliminada de la BD"),
                        to="SISGDDO.area",
                        verbose_name="área*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="entidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=25, unique=True, verbose_name="nombre"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="estado_acuerdo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, null=True, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="estado_cenda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
            ],
        ),
        migrations.CreateModel(
            name="estado_curso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_curso",
                    models.CharField(max_length=25, verbose_name="Estado del curso"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
        ),
        migrations.CreateModel(
            name="estado_entradas_proyecto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=25, verbose_name="nombre*")),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="estado_incidencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        max_length=25, verbose_name="Estado de la incidencia"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
        ),
        migrations.CreateModel(
            name="estado_indicador_objetivos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="estado_licencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nombre de estado*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="estado_propiedad_industrial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Estado de propiedad industrial*",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="estado_proyecto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="formato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
            ],
        ),
        migrations.CreateModel(
            name="fuente_financiamiento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="licencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Número licencia"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=55, unique=True, verbose_name="Nombre licencia*"
                    ),
                ),
                (
                    "fecha_otorgamiento",
                    models.DateField(verbose_name="Fecha otorgamiento*"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha vencimiento*"),
                ),
                (
                    "observaciones",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="SISGDDO.entidad",
                        verbose_name="Entidad*",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="SISGDDO.estado_licencia",
                        verbose_name="Estado de la licencia*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="linea_tematica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=55, unique=True, verbose_name="nombre"),
                ),
                (
                    "anno",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="año"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="modalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre de modalidad*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="modo_formacion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formacion",
                    models.CharField(max_length=25, verbose_name="Modo de formación"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
        ),
        migrations.CreateModel(
            name="pais",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=65,
                        null=True,
                        unique=True,
                        verbose_name="Nombre del país",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="permisos_personalizados",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("grafico_RH", "Ver grafico de RRHH"),
                    ("grafico_Cap", "Ver grafico de CAP"),
                    ("grafico_CA", "Ver grafico de C y A"),
                    ("grafico_D", "Ver grafico de Direccion"),
                    ("grafico_I", "Ver grafico de Inform"),
                    ("grafico_Admin", "Ver grafico de Admin"),
                ],
            },
        ),
        migrations.CreateModel(
            name="proceso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=60,
                        null=True,
                        unique=True,
                        verbose_name="Nombre del proceso*",
                    ),
                ),
                (
                    "abreviatura",
                    models.CharField(max_length=3, verbose_name="Abreviatura*"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="proyecto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no",
                    models.CharField(
                        max_length=10, null=True, unique=True, verbose_name="número*"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=10, null=True, unique=True, verbose_name="código*"
                    ),
                ),
                (
                    "fecha_entrada",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="fecha de entrada*"
                    ),
                ),
                (
                    "nombre_proyecto",
                    models.CharField(
                        max_length=250, null=True, unique=True, verbose_name="nombre*"
                    ),
                ),
                (
                    "aprobacion_consejo",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="aprobación Consejo Editorial",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="fecha de aprobación Consejo Editorial",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="fecha de inicio*"
                    ),
                ),
                (
                    "fecha_interrupcion",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="fecha de interrupción",
                    ),
                ),
                (
                    "causa_interrupcion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="causa de la interrupción",
                    ),
                ),
                (
                    "fecha_terminacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de fin"
                    ),
                ),
                (
                    "fecha_extension",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de extensión"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateField(null=True, verbose_name="fecha de cierre*"),
                ),
                (
                    "costo",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(9999999),
                        ],
                        verbose_name="costo*",
                    ),
                ),
                (
                    "observacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="observacion",
                    ),
                ),
                (
                    "informe_apertura",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ruta/",
                        verbose_name="informe apertura",
                    ),
                ),
                (
                    "informe_cierre",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ruta/",
                        verbose_name="informe cierre",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=models.SET("Área eliminada de la BD"),
                        to="SISGDDO.area",
                        verbose_name="área*",
                    ),
                ),
                (
                    "consecutivo",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyecto",
                        to="SISGDDO.consecutivo",
                        verbose_name="consecutivo*",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=models.SET("Estado eliminado de la BD"),
                        to="SISGDDO.estado_proyecto",
                        verbose_name="estado*",
                    ),
                ),
                (
                    "formato",
                    models.ManyToManyField(
                        related_name="formatos_proyecto",
                        to="SISGDDO.formato",
                        verbose_name="formato",
                    ),
                ),
                (
                    "fuente_financiamiento",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(
                            "Fuente de financiamiento eliminada de la BD"
                        ),
                        to="SISGDDO.fuente_financiamiento",
                        verbose_name="fuente de financiamiento*",
                    ),
                ),
                (
                    "linea_tematica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET("Línea temática eliminada de la BD"),
                        to="SISGDDO.linea_tematica",
                        verbose_name="línea temática",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rol_trabajador_proyecto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, null=True, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="tipo_codigo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="tipo_de_obra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
            ],
        ),
        migrations.CreateModel(
            name="tipo_proyecto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="nombre*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
            ],
        ),
        migrations.CreateModel(
            name="trabajador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, verbose_name="Nombre del Trabajador*"
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=25, verbose_name="Primer Apellido*"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(max_length=25, verbose_name="Segundo Apellido*"),
                ),
                (
                    "ci",
                    models.CharField(
                        blank=True,
                        default=1999,
                        max_length=11,
                        null=True,
                        verbose_name="Carnet de Identidad*",
                    ),
                ),
                ("cargo", models.CharField(max_length=60, verbose_name="Cargo*")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="via_recepcion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=55,
                        unique=True,
                        verbose_name="Nombre vía de recepción*",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
            ],
        ),
        migrations.CreateModel(
            name="conclusion_adicional",
            fields=[
                (
                    "proyecto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="SISGDDO.proyecto",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(verbose_name="Fecha de la conclusión adicional*"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        max_length=250,
                        verbose_name="Descripcion de la conclusión adicional",
                    ),
                ),
            ],
            bases=("SISGDDO.proyecto",),
        ),
        migrations.CreateModel(
            name="dato_adicional",
            fields=[
                (
                    "proyecto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="SISGDDO.proyecto",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del dato adicional*")),
                (
                    "descripcion",
                    models.TextField(
                        max_length=250, verbose_name="Descripcion del dato adicional"
                    ),
                ),
            ],
            bases=("SISGDDO.proyecto",),
        ),
        migrations.CreateModel(
            name="trabajador_proyecto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo*")),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.proyecto",
                        verbose_name="proyecto*",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=models.SET("Rol eliminado de la BD"),
                        to="SISGDDO.rol_trabajador_proyecto",
                        verbose_name="rol*",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.trabajador",
                        verbose_name="trabajador*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="trabajador_consecutivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consecutivo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.consecutivo",
                        verbose_name="consecutivo*",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=models.SET("Rol eliminado de la BD"),
                        to="SISGDDO.rol_trabajador_proyecto",
                        verbose_name="rol*",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.trabajador",
                        verbose_name="trabajador*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="queja",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.TextField(unique=True, verbose_name="Número licencia")),
                (
                    "fecha_receppcion",
                    models.DateTimeField(verbose_name="Fecha recepción*"),
                ),
                ("fecha_cierre", models.DateTimeField(verbose_name="Fecha cierre")),
                (
                    "motivo",
                    models.CharField(
                        max_length=150, verbose_name="Motivo de la queja*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=models.SET("Cliente eliminado de la Base de datos"),
                        to="SISGDDO.cliente",
                        verbose_name="Cliente de la queja*",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=models.SET("Proceso eliminado de la Base de datos"),
                        to="SISGDDO.proceso",
                        verbose_name="Proceso*",
                    ),
                ),
                (
                    "via_recepcion",
                    models.ForeignKey(
                        on_delete=models.SET(
                            "Vía de recepción eliminada de la Base de datos"
                        ),
                        to="SISGDDO.via_recepcion",
                        verbose_name="Cliente de la queja*",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("Tipo de proyecto eliminado de la Base de datos"),
                to="SISGDDO.tipo_proyecto",
                verbose_name="tipo de proyecto*",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tipo_codigo",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("Tipo de código eliminado de la Base de datos"),
                to="SISGDDO.tipo_codigo",
                verbose_name="tipo de código*",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="trabajador",
            field=models.ManyToManyField(
                through="SISGDDO.trabajador_proyecto",
                to="SISGDDO.trabajador",
                verbose_name="rol en el proyecto*",
            ),
        ),
        migrations.CreateModel(
            name="propiedad_industrial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre*")),
                (
                    "fecha_solicitud",
                    models.DateField(verbose_name="Fecha de solicitud*"),
                ),
                (
                    "no_solicitud",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="Número de solicitud*"
                    ),
                ),
                (
                    "no_certificado",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="Número de Certificado*"
                    ),
                ),
                (
                    "concedido_por",
                    models.CharField(max_length=80, verbose_name="Concedido por"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        max_length=80, verbose_name="Tipo de documento legal"
                    ),
                ),
                ("vigente_hasta", models.DateField(verbose_name="Vigente hasta*")),
                (
                    "observaciones",
                    models.TextField(max_length=500, verbose_name="Observaciones"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "clasificacion_dibujo_modelo_industrial",
                    models.ForeignKey(
                        on_delete=models.SET(
                            "Clasificación Dibujo y Modelo Industrial eliminado de la Base de datos"
                        ),
                        to="SISGDDO.clasificacion_dibujo_modelo_industrial",
                        verbose_name="Clasificación dibujo modelo industrial",
                    ),
                ),
                (
                    "clasificacion_elemento_figurativo",
                    models.ForeignKey(
                        on_delete=models.SET(
                            "Clasificación de Elemento Figurativo eliminado de la Base de datos"
                        ),
                        to="SISGDDO.clasificacion_elemento_figurativo",
                        verbose_name="Clasificación de Elementos Figurativos",
                    ),
                ),
                (
                    "clasificacion_patente",
                    models.ForeignKey(
                        on_delete=models.SET(
                            "Clasificación de Patente eliminada de la Base de datos"
                        ),
                        to="SISGDDO.clasificacion_patente",
                        verbose_name="Clasificación de patentes",
                    ),
                ),
                (
                    "clasificacion_productos_servicios",
                    models.ForeignKey(
                        on_delete=models.SET(
                            "Clasificación de productos y servicios eliminada de la Base de datos"
                        ),
                        to="SISGDDO.clasificacion_productos_servicios",
                        verbose_name="Clasificación Productos y Servicios",
                    ),
                ),
                (
                    "clasificacion_viena",
                    models.ForeignKey(
                        on_delete=models.SET(
                            "Clasificación de Viena eliminada de la Base de datos"
                        ),
                        to="SISGDDO.clasificacion_viena",
                        verbose_name="Clasificación de Viena",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=models.SET("Estado eliminado de la Base de datos"),
                        to="SISGDDO.estado_propiedad_industrial",
                        verbose_name="Estado de la licencia*",
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=models.SET(
                            "Modalidad eliminada de la Base de datos*"
                        ),
                        to="SISGDDO.modalidad",
                        verbose_name="Modalidad*",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=models.SET("Pais eliminado"),
                        to="SISGDDO.pais",
                        verbose_name="País*",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proceso",
            name="responsable",
            field=models.ManyToManyField(
                to="SISGDDO.trabajador", verbose_name="Responsable*"
            ),
        ),
        migrations.CreateModel(
            name="procedimiento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Código del procedimiento*",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=60, verbose_name="Nombre del procedimiento*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.proceso",
                        verbose_name="Proceso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="premio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Nombre del premio*",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Fecha*"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="premios/",
                        verbose_name="Planilla de la Reserva",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=models.SET("CITMATEL"),
                        to="SISGDDO.entidad",
                        verbose_name="Entidad*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="plan_medidas",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actividad",
                    models.CharField(max_length=50, verbose_name="Actividad*"),
                ),
                (
                    "titulo_doc",
                    models.CharField(
                        max_length=80, verbose_name="Título del Documento*"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha*")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "acciones",
                    models.ManyToManyField(
                        to="SISGDDO.accion", verbose_name="Acciones*"
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.proceso",
                        verbose_name="Proceso*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="objetivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Nombre de objetivo*",
                    ),
                ),
                (
                    "fecha_definicion",
                    models.DateField(
                        verbose_name="Fecha en que se definió el objetivo*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=models.SET("Área eliminada de la BD"),
                        to="SISGDDO.area",
                        verbose_name="Área*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="notificacion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cantidad de notificaciones*",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=60, verbose_name="Título notificación*"
                    ),
                ),
                (
                    "licencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.licencia",
                        verbose_name="Licencia*",
                    ),
                ),
                (
                    "premio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.premio",
                        verbose_name="Premio*",
                    ),
                ),
                (
                    "propiedad_industrial",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.propiedad_industrial",
                        verbose_name="Propiedad intelectual*",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="licencia",
            name="proceso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="SISGDDO.proceso",
                verbose_name="Proceso*",
            ),
        ),
        migrations.AddField(
            model_name="licencia",
            name="responsable",
            field=models.ManyToManyField(
                help_text="Escoja el responsable",
                to="SISGDDO.trabajador",
                verbose_name="Responsable*",
            ),
        ),
        migrations.CreateModel(
            name="indicador_objetivos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, null=True, verbose_name="Nombre del indicador*"
                    ),
                ),
                (
                    "evaluacion",
                    models.FloatField(verbose_name="Evaluación del indicador*"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "estado",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("Estado eliminado"),
                        to="SISGDDO.estado_indicador_objetivos",
                        verbose_name="Estado*",
                    ),
                ),
                (
                    "objetivo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objetivos",
                        to="SISGDDO.objetivo",
                        verbose_name="Objetivo*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="indicador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Nombre del indicador*"
                    ),
                ),
                (
                    "evaluacion",
                    models.FloatField(verbose_name="Evaluación del indicador*"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "proceso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.proceso",
                        verbose_name="Proceso*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="incidencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateField(
                        verbose_name="Fecha de recepcion de la incidencia*"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de cierre de la incidencia",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=250, verbose_name="Descripción de la incidencia*"
                    ),
                ),
                (
                    "respuesta",
                    models.TextField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Respuesta dada a la incidencia",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=models.SET("Estado eliminado"),
                        to="SISGDDO.estado_incidencia",
                        verbose_name="Estado de la incidencia",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET("Proceso eliminado"),
                        to="SISGDDO.proceso",
                        verbose_name="Proceso que da respuesta a la incidencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="entrada_proyecto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_entrada",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="fecha*"
                    ),
                ),
                (
                    "fecha_salida",
                    models.DateField(null=True, verbose_name="Fecha de salida"),
                ),
                (
                    "dictamen",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="entradas_proyectos/",
                        verbose_name="informe apertura",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "entregado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.trabajador",
                        verbose_name="Trabajador que entrega",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SISGDDO.estado_entradas_proyecto",
                        verbose_name="Estado entrada proyecto",
                    ),
                ),
                (
                    "formato",
                    models.ManyToManyField(
                        to="SISGDDO.formato", verbose_name="Formato*"
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.proyecto",
                        verbose_name="Proyecto*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="eficacia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anno",
                    models.DateField(
                        default="2022-12-20", verbose_name="Año análisis de eficacia*"
                    ),
                ),
                (
                    "semestre",
                    models.BooleanField(
                        default=False,
                        help_text="Si es False es el primer semestre si no es el segundo semestre",
                        verbose_name="Semestre*",
                    ),
                ),
                ("eficaz", models.BooleanField(default=False, verbose_name="Eficaz*")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "evaluado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(
                            "Trabajador eliminado de la Base de datos"
                        ),
                        related_name="evaluado_por_eficacia",
                        to="SISGDDO.trabajador",
                        verbose_name="Evaluado por*",
                    ),
                ),
                (
                    "indicador",
                    models.ManyToManyField(
                        to="SISGDDO.indicador", verbose_name="Indicador"
                    ),
                ),
                (
                    "proceso_asociado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos_asociados",
                        to="SISGDDO.proceso",
                        verbose_name="Proceso asociado*",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(
                            "Trabajador eliminado de la Base de datos"
                        ),
                        related_name="responsable_eficacia",
                        to="SISGDDO.trabajador",
                        verbose_name="Responsable*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="curso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Nombre del curso*"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(null=True, verbose_name="Fecha de inicio*"),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                (
                    "duracion_diaria",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duración del curso en horas",
                    ),
                ),
                (
                    "precio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precio del curso"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "entidad",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("Entidad eliminada"),
                        to="SISGDDO.entidad",
                        verbose_name="Entidad*",
                    ),
                ),
                (
                    "estado_curso",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("Estado del curso eliminado"),
                        to="SISGDDO.estado_curso",
                        verbose_name="Estado del curso",
                    ),
                ),
                (
                    "modo_formacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("Modo de formación eliminado de la BD"),
                        to="SISGDDO.modo_formacion",
                        verbose_name="Modo de formación*",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consecutivo",
            name="estado",
            field=models.ForeignKey(
                on_delete=models.SET("Estado eliminado de la BD"),
                to="SISGDDO.estado_proyecto",
                verbose_name="estado*",
            ),
        ),
        migrations.AddField(
            model_name="consecutivo",
            name="formato",
            field=models.ManyToManyField(
                related_name="formatos_consecutivo",
                to="SISGDDO.formato",
                verbose_name="formato",
            ),
        ),
        migrations.AddField(
            model_name="consecutivo",
            name="fuente_financiamiento",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("Fuente de financiamiento eliminada de la BD"),
                to="SISGDDO.fuente_financiamiento",
                verbose_name="fuente de financiamiento*",
            ),
        ),
        migrations.AddField(
            model_name="consecutivo",
            name="linea_tematica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET("Línea temática eliminada de la BD"),
                to="SISGDDO.linea_tematica",
                verbose_name="línea temática",
            ),
        ),
        migrations.AddField(
            model_name="consecutivo",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("Tipo de proyecto eliminado de la Base de datos"),
                to="SISGDDO.tipo_proyecto",
                verbose_name="tipo de proyecto*",
            ),
        ),
        migrations.AddField(
            model_name="consecutivo",
            name="tipo_codigo",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("Tipo de código eliminado de la Base de datos"),
                to="SISGDDO.tipo_codigo",
                verbose_name="tipo de código*",
            ),
        ),
        migrations.AddField(
            model_name="consecutivo",
            name="trabajador",
            field=models.ManyToManyField(
                through="SISGDDO.trabajador_consecutivo",
                to="SISGDDO.trabajador",
                verbose_name="rol en el proyecto*",
            ),
        ),
        migrations.CreateModel(
            name="capacitacion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio*")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(max_length=10, verbose_name="Resultado del curso"),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "costo_diario_trabajador",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Costo diario del trabajador en la capacitación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=models.SET("Curso eliminado de la BD"),
                        to="SISGDDO.curso",
                        verbose_name="Nombre del curso*",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=models.SET("Estado del curso eliminado"),
                        to="SISGDDO.estado_curso",
                        verbose_name="Estado del curso",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=models.SET("Trabajador eliminado"),
                        to="SISGDDO.trabajador",
                        verbose_name="Trabajador*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="autor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="nombre y apellidos del autor*",
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=11, verbose_name="carnet de identidad*"
                    ),
                ),
                (
                    "pasaporte",
                    models.CharField(max_length=15, verbose_name="pasaporte"),
                ),
                (
                    "domicilio_legal",
                    models.CharField(max_length=250, verbose_name="domicilio legal*"),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="correo electrónico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="teléfono"
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.pais",
                        verbose_name="nacionalidad*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="auditoria_interna",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de auditoría*")),
                (
                    "titulo",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Título del informe*"
                    ),
                ),
                (
                    "objetivos",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Objetivos de la auditoría",
                    ),
                ),
                (
                    "alcance",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Alcance de la auditoría",
                    ),
                ),
                (
                    "criterios",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Criterios de la auditoría",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Observaciones de la auditoría",
                    ),
                ),
                (
                    "informe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dictamenes/",
                        verbose_name="Informe de la auditoria*",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "proceso",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("Proceso eliminado"),
                        to="SISGDDO.proceso",
                        verbose_name="Proceso*",
                    ),
                ),
                (
                    "responsable",
                    models.ManyToManyField(
                        to="SISGDDO.trabajador", verbose_name="Responsable*"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="auditoria_externa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(null=True, verbose_name="Fecha de emisión*"),
                ),
                (
                    "registro",
                    models.CharField(
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Número de registro*",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Título del informe*"
                    ),
                ),
                (
                    "resultados",
                    models.BooleanField(default=True, verbose_name="Resultado"),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "informe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dictamenes/",
                        verbose_name="Informe de la auditoria*",
                    ),
                ),
                (
                    "plan_medidas",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dictamenes/",
                        verbose_name="Plan de medidas*",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=models.SET("Entidad eliminada"),
                        to="SISGDDO.entidad",
                        verbose_name="Entidad*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="aspecto_medir_eficacia_indicador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="Nombre de aspecto*"),
                ),
                (
                    "calificacion",
                    models.IntegerField(
                        null=True, verbose_name="Calificación de aspecto*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.indicador",
                        verbose_name="Indicador*",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="acuerdo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="Número de acuerdo*",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Nombre del acuerdo*"
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Día/Mes/Año ejemplo 01/01/2020",
                        verbose_name="Fecha de tomado el acuerdo*",
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateField(
                        help_text="Día/Mes/Año ejemplo 01/01/2020",
                        verbose_name="Fecha límite para cumplir",
                    ),
                ),
                (
                    "fecha_cumplimiento",
                    models.DateField(
                        help_text="Día/Mes/Año ejemplo 01/01/2020",
                        verbose_name="Fecha de cumplido el acuerdo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        null=True, verbose_name="Observaciones sobre el acuerdo*"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "estado_acuerdo",
                    models.ForeignKey(
                        on_delete=models.SET("Estado eliminado"),
                        to="SISGDDO.estado_acuerdo",
                        verbose_name="Estado de acuerdo*",
                    ),
                ),
                (
                    "responsable",
                    models.ManyToManyField(
                        to="SISGDDO.trabajador", verbose_name="Responsable*"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="accion_indicador_objetivos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Nombre de la acción*"
                    ),
                ),
                (
                    "evaluacion",
                    models.FloatField(verbose_name="Evaluación de la acción*"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo*")),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("Area eliminado de la BD"),
                        to="SISGDDO.area",
                        verbose_name="Area a la que pertenece*",
                    ),
                ),
                (
                    "indicador_objetivos",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("Indicador eliminado de la BD"),
                        to="SISGDDO.indicador_objetivos",
                        verbose_name="Indicador al que pertenece*",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accion",
            name="responsable",
            field=models.ManyToManyField(
                to="SISGDDO.trabajador", verbose_name="Responsble*"
            ),
        ),
        migrations.CreateModel(
            name="sosi",
            fields=[
                (
                    "consecutivo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="SISGDDO.consecutivo",
                    ),
                ),
                (
                    "numero_salva",
                    models.CharField(max_length=10, verbose_name="Número de salva*"),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha de entrega*"
                    ),
                ),
                (
                    "anno",
                    models.CharField(
                        max_length=4,
                        null=True,
                        verbose_name="Año al que corresponde la salva",
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Autor del proyecto",
                    ),
                ),
                (
                    "ubicacion_salva",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Ubicación de la salva",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                ("eliminado", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "especialista",
                    models.ForeignKey(
                        on_delete=models.SET("Trabajador eliminado"),
                        to="SISGDDO.trabajador",
                        verbose_name="Trabajador que entrega*",
                    ),
                ),
            ],
            bases=("SISGDDO.consecutivo",),
        ),
        migrations.CreateModel(
            name="cenda",
            fields=[
                (
                    "consecutivo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="SISGDDO.consecutivo",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateField(null=True, verbose_name="fecha de solicitud*"),
                ),
                (
                    "fecha_registro",
                    models.DateField(null=True, verbose_name="fecha de registro*"),
                ),
                (
                    "titulo",
                    models.CharField(max_length=150, null=True, verbose_name="título*"),
                ),
                (
                    "codigo_registro",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="No Registro"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.autor",
                        verbose_name="datos del autor*",
                    ),
                ),
                (
                    "tipo_de_obra",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SISGDDO.tipo_de_obra",
                        verbose_name="tipo de obra*",
                    ),
                ),
            ],
            bases=("SISGDDO.consecutivo",),
        ),
    ]
