# Generated by Django 4.1.3 on 2023-01-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SISGDDO", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambiarlogotipo",
            name="fecha_cambio",
            field=models.DateField(
                default="2023-01-16", verbose_name="Fecha de Cambio del Logotipo"
            ),
        ),
        migrations.AlterField(
            model_name="eficacia",
            name="anno",
            field=models.DateField(
                default="2023-01-16", verbose_name="Año análisis de eficacia*"
            ),
        ),
    ]
