# Generated by Django 4.1.3 on 2023-02-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SISGDDO", "0004_alter_cambiarlogotipo_fecha_cambio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambiarlogotipo",
            name="fecha_cambio",
            field=models.DateField(
                default="2023-02-08", verbose_name="Fecha de Cambio del Logotipo"
            ),
        ),
        migrations.AlterField(
            model_name="eficacia",
            name="anno",
            field=models.DateField(
                default="2023-02-08", verbose_name="Año análisis de eficacia*"
            ),
        ),
    ]
