# Generated by Django 4.1.3 on 2023-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0009_alter_cambiarlogotipo_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afectaciones',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='No.*')),
                ('fecha_recepcion', models.DateTimeField(blank=True, verbose_name='Fecha de Entrada*')),
                ('afectacion', models.CharField(max_length=80, verbose_name='Afectacion reportada*')),
                ('mesplaneado', models.DateField(blank=True, verbose_name='Mes Planeado Resolverse*')),
                ('fechacierre', models.DateTimeField(blank=True, verbose_name='Fecha de cierre*')),
                ('observacionesactual', models.CharField(max_length=250, verbose_name='Observaciones*')),
                ('observacionesfutura', models.CharField(max_length=250, verbose_name='Observaciones*')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado*')),
            ],
        ),
        migrations.CreateModel(
            name='PlanesdeTrabajo',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='No.*')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripcion*')),
                ('fecha', models.DateTimeField(blank=True, verbose_name='Fecha de Reunion*')),
                ('hora', models.TimeField(blank=True, verbose_name='Hora Programada*')),
                ('lugar', models.CharField(max_length=80, verbose_name='Lugar Previsto*')),
            ],
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='informe',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='eliminado',
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2023-05-10', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2023-05-10', verbose_name='Año análisis de eficacia*'),
        ),
    ]
