# Generated by Django 4.1.3 on 2023-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0013_alter_cambiarlogotipo_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='proceso',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado'), to='SISGDDO.trabajador', verbose_name='Trabajador que reporta la incidencia*'),
        ),
    ]
